### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by pcace** [okainov/ebay-kleinanzeigen#3]
Hi, 

is there any small howto to run your software? It sounds interesting, but where do i put links?

Cheers!

**Comment by okainov** [comment]
Thanks for asking!

But isn't 8t mentioned in the readme already? It's Telegram bot, thus you need to have not token (which you should have gotten from @BotFather). And then just

```
docker-compose build
docker-compose up -d
```

For polling mode this should work even locally. For webhook mode you should run in in VPS or so which is accessible via HTTPS.

When the bot is run, just send the links to the bot via telegram

**Comment by pcace** [comment]
Hi, thank you for your fast reply!!
so there is a webinterface? 
on what port should it be running on?

**Comment by pcace** [comment]
so this is what i have found: (but i dont know how to fix it).
It probably means, that there must be some way to have the token/chatID set besides in utils.py (i have set it there, it looks like this: 


    return Bot(token=os.getenv("954129146:AAFF3FtOM_-thisisnottherealid-6szTY6GXuLTyg"), request=request)

)?
```
root@mail:/opt/ebay-kleinanzeigen# docker-compose logs
Attaching to ebay-kleinanzeigen_tg-bot_1
tg-bot_1  | Traceback (most recent call last):
tg-bot_1  |   File "/app/main.py", line 161, in <module>
tg-bot_1  |     main()
tg-bot_1  |   File "/app/main.py", line 130, in main
tg-bot_1  |     updater = Updater(bot=utils.get_bot(), use_context=True)
tg-bot_1  |   File "/app/utils.py", line 18, in get_bot
tg-bot_1  |     return Bot(token=os.getenv("TG_TOKEN"), request=request)
tg-bot_1  |   File "/usr/local/lib/python3.8/site-packages/telegram/bot.py", line 90, in __init__
tg-bot_1  |     self.token = self._validate_token(token)
tg-bot_1  |   File "/usr/local/lib/python3.8/site-packages/telegram/bot.py", line 142, in _validate_token
tg-bot_1  |     raise InvalidToken()
tg-bot_1  | telegram.error.InvalidToken: Invalid token
```

**Comment by okainov** [comment]
Instead of modifying code, update file .env and put the token there. Also you might want to set debug=1 or so

**Comment by pcace** [comment]
aahmm, 
sorry, that was stupid from me.
i got a little bit further: the bot now said "hi" in the chat.

but how am i supposed to add links?

sorry for all the dump questions..
and thank you for your time!

**Comment by pcace** [comment]
> aahmm,
> sorry, that was stupid from me.
> i got a little bit further: the bot now said "hi" in the chat.
> 
> but how am i supposed to add links?
> 
> sorry for all the dump questions..
> and thank you for your time!

**Comment by pcace** [comment]
I am sorry, i thought i made it now, but i still do not get how i would add links to the bot..
but i got this now in the logs:

```
docker-compose logs
Attaching to ebay-kleinanzeigen_tg-bot_1
tg-bot_1  | 2021-05-24 20:22:15,291 [INFO] Started echo
tg-bot_1  | 2021-05-24 20:22:15,453 [INFO] Added job "echo" to job store "default"
tg-bot_1  | 2021-05-24 20:22:15,454 [INFO] Scheduled job

```

**Comment by okainov** [comment]
@pcace it should work just by sending like to the bot. One at a time, so only one is monitored

**Comment by pcace** [comment]
ok, 

then i have understood it correctly, but something seems to be off... this is the Log:

```
Starting ebay-kleinanzeigen_tg-bot_1 ... done
Attaching to ebay-kleinanzeigen_tg-bot_1
tg-bot_1  | 2021-05-25 09:08:57,950 [INFO] Started echo
tg-bot_1  | 2021-05-25 09:08:58,056 [INFO] Added job "echo" to job store "default"
tg-bot_1  | 2021-05-25 09:08:58,057 [INFO] Scheduled job
tg-bot_1  | 2021-05-25 09:09:01,893 [INFO] Started echo
tg-bot_1  | 2021-05-25 09:23:58,061 [INFO] Running job "echo (trigger: interval[0:15:00], next run at: 2021-05-25 09:23:58 UTC)" (s                                                        cheduled at 2021-05-25 09:23:58.055943+00:00)
tg-bot_1  | 2021-05-25 09:23:58,062 [INFO] Started echo
tg-bot_1  | 2021-05-25 09:23:58,151 [ERROR] Job "echo (trigger: interval[0:15:00], next run at: 2021-05-25 09:38:58 UTC)" raised an                                                         exception
tg-bot_1  | Traceback (most recent call last):
tg-bot_1  |   File "/usr/local/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
tg-bot_1  |     retval = job.func(*job.args, **job.kwargs)
tg-bot_1  |   File "/app/main.py", line 121, in echo
tg-bot_1  |     last_items[chat_id] = {'last_item': items[0].url, 'search_url': url}
tg-bot_1  | IndexError: list index out of range

```

i did send this to the Bot:

"https://www.ebay-kleinanzeigen.de/s-wohnung/k0"

Any Idea?

Cheers and thanks!!!

**Comment by Bonbonita** [comment]
Hey, I'm wondering if I doing something wrong because I have the same issue as above. Is there is any fix to it?

**Comment by okainov** [comment]
Seems should be better now with #6 merged, please try again :)
