### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mlupoo** [okainov/ebay-kleinanzeigen#5]
Hi, I can not understand what exactly the error is. Does somebody has any idea?
```
[INFO] Running job "echo (trigger: interval[0:02:00], next run at: 2022-04-20 20:21:34 UTC)" (scheduled at 2022-04-20 20:19:34.563367+00:00)

[INFO] Started echo

[ERROR] Job "echo (trigger: interval[0:02:00], next run at: 2022-04-20 20:21:34 UTC)" raised an exception

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job

    retval = job.func(*job.args, **job.kwargs)

  File "/app/main.py", line 121, in echo

    last_items[chat_id] = {'last_item': items[0].url, 'search_url': url}

IndexError: list index out of range
```

**Comment by mlupoo** [comment]
Hello, I think I found the problem.

`[INFO] <!DOCTYPE html><html><head><title>Error Page</title><style type="text/css">html{font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:1em}.center-box{margin: 20% auto auto auto;width: 50%;border: 1px solid #dcdcdc;padding: 1em;}

</style><title>Security Violation (403)</title></head></head><body>

<div class="center-box">

    <h3>www.ebay-kleinanzeigen.de&nbsp;|&nbsp;Access denied (403)</h3>

    <h4>Current session has been terminated.</h2>

    <p>For further information, do not hesitate to contact us.</p>

    <p>Ref: <span id="addr">11.22.33.44</span>&nbsp;<span id="time">1650562974</span></p>

</div></body><script>document.getElementById("time").innerHTML = (new Date()).toISOString()</script>

</html>`

**Comment by larsf96** [comment]
This repo seems to be outdated. Some DOM elements changed and at least for me, I'm getting HTTP 403 when accessing ebay.
I will do a pull request do fix this

**Comment by larsf96** [comment]
@mlupoo The pull request should fix this problem
